name: My test
on:
  workflow_dispatch:
  push:
    branches:
      - master

env: 
   RECORD_KEY: ${{ secrets.RECORD_KEY }} 

jobs:
  testingONE:
    strategy:
      matrix:
        run_number: [1, 2] 
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
      options: --user 1001
    steps:
      - name: Add env vars
        run: echo $RECORD_KEY
      - name: Get the project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --force
      - name: Run tests
        run: npm run cypress:app
      - name: Generate reports
        run: npm run generate-report
      - name: Save reports
        uses: actions/upload-artifact@v3
        with:
          path: mochawesome-report
          name: Test Report
      - name: Get reports
        uses: actions/download-artifact@v3
        with:
          name: Test Report

  testingTWO:
      runs-on: ubuntu-latest
      container: 
        image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
        options: --user 1001
      steps:
          - name: Get the project code
            uses: actions/checkout@v4
          - name: Install dependencies
            run: npm install --force
          - name: Run tests
            run: npm run cypress:app
          - name: Generate reports
            run: npm run generate-report
          - name: Save reports
            uses: actions/upload-artifact@v3
            with:
               path: mochawesome-report
               name: Test Report
          - name: Get reports
            uses: actions/download-artifact@v3
            with:
             name: Test Report


        

  
