name: My test
on:
  workflow_dispatch:
  push:
    branches:
      - master

env: 
    APP_VER: production

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get the project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --force
      - name: Run tests
        run: npm run cypress:app
      - name: Save reports
        uses: actions/upload-artifact@v3
      - name: Get reports
        uses: actions/download-artifact@v3
        with:
          path: mochawesome-report
          name: Test Report

  
